### ISSUE TITLE
Ir revisando lo que voy re-escribiendo

### ISSUE THREAD

**Issue by unintendedbear** [geneura-papers/2014-2015-COMCOM-MUSES_vs_SotA_BYOD_Systems#10]
Como tengo poco o nada de tiempo, anoche estuve reescribiendo parte y esta noche haré lo mismo, hasta que reescriba todo lo que haga falta (que parece que es todo) entre esta noche y mañana. Tampoco es solo reescribir, sino que las características de cada herramienta las escribí el primer año de Muses y el proyecto está acabando, así que me tengo que meter en cada página y actualizar la información.

Mejor si se va revisando poco a poco. De modo que si tenéis un hueco, os lo agradecería.

Paloma.

**Comment by amorag** [comment]
Ok.
Aunque seguiré horarios similares para hacerlo. :(

**Comment by unintendedbear** [comment]
Revisado todo por Fergu, lo doy por cerrado.
