### ISSUE TITLE
Justificar que los métodos de data mining y de aprendizaje requieren una gran capacidad computacional

### ISSUE THREAD

**Issue by amorag** [geneura-papers/2014-2015-COMCOM-MUSES_vs_SotA_BYOD_Systems#13]
Buscar un par de referencias de esto para justificar la necesidad de un servidor en MUSES.

**Comment by JJ** [comment]
¿Por? Los móviles tienen poca potencia...

**Comment by fergunet** [comment]
Siento ponerlo aquí porque aún no me he bajado el paper y no sé donde va. Abajo está el bibtex.

Data Mining is not about analysing small datasets using traditional techniques \cite{Cios07DataMining}, but dealing with massively large amounts of data, so in the MUSES project, part of the high computational cost methods to apply must be derived to a high-performance server, as the mobile devices do not count with enough computational power.

@incollection{Cios07DataMining,
year={2007},
isbn={978-0-387-33333-5},
booktitle={Data Mining: A Knowledge Discovery Approach},
doi={10.1007/978-0-387-36795-8_1},
title={Introduction},
url={http://dx.doi.org/10.1007/978-0-387-36795-8_1},
publisher={Springer US},
author={Cios, Krzysztof J. and Swiniarski, Roman W. and Pedrycz, Witold and Kurgan, Lukasz A.},
pages={3-7},
language={English}
}

**Comment by unintendedbear** [comment]
Gracias Fergu, y JJ, creo que esto es para justificar el  uso de arquitectura cliente-servidor (más bien el servidor).

**Comment by amorag** [comment]
Efectivamente.
Todos estos últimos Issues son para justificar las respuestas al revisor que debemos dar.
Vamos, para hacer lo que pide.

Los móviles tienen poca potencia, pero podría ser suficiente para hacer estas tareas de data mining/machine learning...

Hay un documento de texto en el mismo repo con las respuestas.
Lo pasaré a formato bonito antes de subirlo.

Un saludo.

**Comment by amorag** [comment]
Lo he metido en el artículo, pero necesitamos una justificación con más peso.
@fergunet busca alguna referencia sobre el manejo de big data o data mining/machine learning aplicado sobre big data. ;)

Gracias.

**Comment by amorag** [comment]
Bueno, teníamos una referencia ya de big data.
Si encuentras algo que indique lo exigentes (computacionalmente) que son estas técnicas lo ponemos, si no, así mismo está bien, creo yo. ;)

**Comment by fergunet** [comment]
@amorag la frase que yo he puesto está tal cual (bueno, no es un copypaste) de la referencia que he puesto. El autor dice tal cual en ese capítulo que cito "DM no se puede usar en cosas chiquiticas, ya que requiere la leche de recursos computacionales". Si quieres mueve el cite al final:

_Data Mining is not about analysing small datasets using traditional techniques, but dealing with massively large amounts of data \cite{Cios07DataMining}_ (amos, que tal cual lo dice el señor Cios en esa referencia)

De todas formas, he encontrado otra referencia. Añade la siguiente frase también.

_Also, Data Mining with Big Data implies to deal with terabytes, or even petabytes of data, so its algorithms requires high computational costs \cite{Shirkhorshidi14Review}._

@inproceedings{Shirkhorshidi14Review,
  author    = {Ali Seyed Shirkhorshidi and
               Saeed Reza Aghabozorgi and
               Ying Wah Teh and
               Tutut Herawan},
  title     = {Big Data Clustering: {A} Review},
  booktitle = {Computational Science and Its Applications - {ICCSA} 2014 - 14th International
               Conference, Guimar{~{a}}es, Portugal, June 30 - July 3, 2014, Proceedings,
               Part {V}},
  pages     = {707--720},
  url       = {http://dx.doi.org/10.1007/978-3-319-09156-3_49},
  editor    = {Beniamino Murgante and
               Sanjay Misra and
               Ana Maria A. C. Rocha and
               Carmelo Maria Torre and
               Jorge Gustavo Rocha and
               Maria Irene Falc{~{a}}o and
               David Taniar and
               Bernady O. Apduhan and
               Osvaldo Gervasi},
  series    = {Lecture Notes in Computer Science},
  volume    = {8583},
  publisher = {Springer},
  year      = {2014},
}

**Comment by amorag** [comment]
Ahm, que era una frase literal de la cita.

Lo adapto entonces.

Lo que pasa es que porque lo diga el señor Cios no justifica el uso de un servidor aparte, es decir, que DM pueden hacerlo los móviles actuales. :D

Lo que has encontrado Big Data sí que mola más. ;)

¡Grachas!

De: Pablo García Sánchez [mailto:notifications@github.com] 
Enviado el: jueves, 16 de abril de 2015 13:36
Para: geneura-papers/2014-2015-COMCOM-MUSES_vs_SotA_BYOD_Systems
CC: Antonio Mora
Asunto: Re: [2014-2015-COMCOM-MUSES_vs_SotA_BYOD_Systems] Justificar que los métodos de data mining y de aprendizaje requieren una gran capacidad computacional (#13)

@amorag https://github.com/amorag  la frase que yo he puesto está tal cual (bueno, no es un copypaste) de la referencia que he puesto. El autor dice tal cual en ese capítulo que cito "DM no se puede usar en cosas chiquiticas, ya que requiere la leche de recursos computacionales". Si quieres mueve el cite al final:

Data Mining is not about analysing small datasets using traditional techniques, but dealing with massively large amounts of data \cite{Cios07DataMining} (amos, que tal cual lo dice el señor Cios en esa referencia)

De todas formas, he encontrado otra referencia. Añade la siguiente frase también.

Also, Big Data implies to deal with terabytes, or even petabytes of data, so its algorithms requires high computational costs \cite{Shirkhorshidi14Review}.

@inproceedings{Shirkhorshidi14Review,
author = {Ali Seyed Shirkhorshidi and
Saeed Reza Aghabozorgi and
Ying Wah Teh and
Tutut Herawan},
title = {Big Data Clustering: {A} Review},
booktitle = {Computational Science and Its Applications - {ICCSA} 2014 - 14th International
Conference, Guimar{~{a}}es, Portugal, June 30 - July 3, 2014, Proceedings,
Part {V}},
pages = {707--720},
url = {http://dx.doi.org/10.1007/978-3-319-09156-3_49},
editor = {Beniamino Murgante and
Sanjay Misra and
Ana Maria A. C. Rocha and
Carmelo Maria Torre and
Jorge Gustavo Rocha and
Maria Irene Falc{~{a}}o and
David Taniar and
Bernady O. Apduhan and
Osvaldo Gervasi},
series = {Lecture Notes in Computer Science},
volume = {8583},
publisher = {Springer},
year = {2014},
}

—
Reply to this email directly or view it on GitHub https://github.com/geneura-papers/2014-2015-COMCOM-MUSES_vs_SotA_BYOD_Systems/issues/13#issuecomment-93713666 .  https://github.com/notifications/beacon/AC6-WkYhchtPS9OtPwBJYSS9iQYoIScPks5n_5YogaJpZM4EBJ85.gif 

No se encontraron virus en este mensaje.
Comprobado por AVG - www.avg.com
Versión: 2015.0.5863 / Base de datos de virus: 4331/9551 - Fecha de publicación: 04/16/15

---

No se encontraron virus en este mensaje.
Comprobado por AVG - www.avg.com
Versión: 2015.0.5863 / Base de datos de virus: 4331/9551 - Fecha de publicación: 04/16/15

**Comment by unintendedbear** [comment]
¿Al final esto se ha incluído en el paper? ¿Lo incluyo? ¿Dónde?

**Comment by amorag** [comment]
Hola, sí lo incluí y lo comenté en el commit.
Se me olvidó cerrar el Issue, eso sí.
