### ISSUE TITLE
Explicación de Anonimización y Privacidad en MUSES

### ISSUE THREAD

**Issue by amorag** [geneura-papers/2014-2015-COMCOM-MUSES_vs_SotA_BYOD_Systems#18]
No sé si al final se anonimiza algo (datos personales y demás creo que sí o que simplemente no se usan) y privacidad se respeta con el hard limit.
Aunque también se implementará el soft limit.

Citar algún deliverable que pueda servir, si lo hay.

RESPONDER A ESTO:
Page 18, lines 20-37 hint about the importance of privacy enhancing technologies in a system that monitors the activity of the user and sends this activity to a centralized server to be "anonymously managed". 
Further information about how the system manages this information is needed (does private information ever leaves the personal devices? Which activity is monitored and collected?), as well as an explanation about how these data is anonymized. Is it anonymized at the mobile phone? Or in the server's database?

**Comment by JJ** [comment]
¿hay un documento aparte para esto?
