### ISSUE TITLE
Tratar el tema del futuro

### ISSUE THREAD

**Issue by fergunet** [geneura-papers/2014-2015-COMCOM-MUSES_vs_SotA_BYOD_Systems#19]
Veo que muchas partes del paper son "MUSES hará tal cosa", y puede ser un poco peliagudo hacer un paper de algo que no se ha hecho. Creo que ya no da tiempo a cambiar la orientación, pero otra opción sería vender MUSES como una arquitectura abstracta que sirve para tal y tal, y que debería usarse como base para desarrollar cosas concretas (que son las que están desarrollándose ahora).

Sé que ya es bastante tarde, pero si queréis me encargo de cambiar el enfoque.

**Comment by unintendedbear** [comment]
Ya, también lo ha comentado @JJ en el commit. Esto es básicamente porque esto se escribí cuando no estaba ni terminada la arquitectura. Habría que haberlo cambiado antes de enviarlo la primera vez.

Ya como quieras. Me imaginaba que habría que hacer esto pero es que es modificarlo casi todo y yo sinceramente no he podido. Si ves que es mucho, nos repartimos mitad y mitad.

**Comment by fergunet** [comment]
Otra opción es decir que está hecho y punto xD (vamos, quitar todos los will y would)

**Comment by deantares** [comment]
Yo también lo he visto, y queda un poco raro, ya que pareciera que no "está" hecho. Si decís de cambiarlo, echo una mano.

**Comment by unintendedbear** [comment]
Qué va :/ modificando las cosas que tenía asignadas he visto que está todo cogido con pinzas y sin explicar casi nada. Vaya, como estaba en el artículo que escribí hace dos años ya.

**Comment by JJ** [comment]
Bueno, vamos a intentarlo. Lo que se haya hecho, se pone. Lo que no, se
queda en "will". Paloma, tú eres quien tienes mejor conocimiento del tema...

El 16 de abril de 2015, 19:13, Paloma de las Cuevas Delgado <
notifications@github.com> escribió:

> Qué va :/ modificando las cosas que tenía asignadas he visto que está todo
> cogido con pinzas y sin explicar casi nada. Vaya, como estaba en el
> artículo que escribí hace dos años ya.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/geneura-papers/2014-2015-COMCOM-MUSES_vs_SotA_BYOD_Systems/issues/19#issuecomment-93787687
> .

## 

JJ

**Comment by unintendedbear** [comment]
Vale. Estoy recogiendo la factura del catering de la reunión de muses, en 20 minutos me pongo.

**Comment by JJ** [comment]
Lo conveniente sería resolverlo.

**Comment by amorag** [comment]
Cuidado que se habían quedado cosas como 'is be' en el cambio. ;)

**Comment by JJ** [comment]
¿Se han resuelto esas cosas?

**Comment by unintendedbear** [comment]
Que yo recuerde @fergunet estuvo cambiándolo todo. Yo en lo del refinement he estado poniendo cosas en presente también. Fergu, si quieres darle otro repaso...

**Comment by amorag** [comment]
Hace falta otro vistazo en profundidad, porque la otra vez se hizo algo precipitado y quedaron errrores como los que he apuntado. 

Ya no hay de esos, pero seguramente haya algún otro error o incoherencia. 

@fergunet, échale un ojo porfa.

**Comment by JJ** [comment]
A ver, ¿qué pasa con este issue? ¿Lo resuelve alguien? ¿Nadie?
