### ISSUE TITLE
Leer surveys

### ISSUE THREAD

**Issue by JJ** [geneura-papers/2014-2015-COMCOM-MUSES_vs_SotA_BYOD_Systems#2]
Mirar la parte de seguridad corporativa de este survey

http://ieeexplore.ieee.org/xpl/login.jsp?tp=&arnumber=6779901&url=http%3A%2F%2Fieeexplore.ieee.org%2Fxpls%2Fabs_all.jsp%3Farnumber%3D6779901

Ya está añadido a la bibliografía.

**Comment by unintendedbear** [comment]
Estoy leyendo esto, a ver si lo puedo resumir para la noche.

**Comment by unintendedbear** [comment]
Por lo que he leído, a lo mejor sería interesante describir cómo MUSES se encarga de los puntos que estos autores indican como recomendaciones para aumentar la seguridad. Incluso de cómo MUSES protegería al usuario frente a los ataques descritos en la parte de Network threats.

O eso o decir que nuestro survey completa al suyo porque ellos no tienen en cuenta el BYOD.

¿Cómo lo veis?

**Comment by JJ** [comment]
Bien.

El 6 de abril de 2015, 20:14, Paloma de las Cuevas Delgado <
notifications@github.com> escribió:

> Por lo que he leído, a lo mejor sería interesante describir cómo MUSES se
> encarga de los puntos que estos autores indican como recomendaciones para
> aumentar la seguridad. Incluso de cómo MUSES protegería al usuario frente a
> los ataques descritos en la parte de Network threats.
> 
> O eso o decir que nuestro survey completa al suyo porque ellos no tienen
> en cuenta el BYOD.
> 
> ¿Cómo lo veis?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/geneura-papers/2014-2015-COMCOM-MUSES_vs_SotA_BYOD_Systems/issues/2#issuecomment-90180623
> .

## 

JJ

**Comment by unintendedbear** [comment]
Al final lo he incluído como referencia pero no veo sitio para meterlo en el state of the art. Eso y que me voy a tirar por la ventana.
