### ISSUE TITLE
Tabla Comparativa final

### ISSUE THREAD

**Issue by deantares** [geneura-papers/2014-2015-COMCOM-MUSES_vs_SotA_BYOD_Systems#20]
¿Sería muy complicado hacer una tabla de características de los sistemas comparados? Realmente, echo en falta algo así.

Tampoco es que sea para hacer algo muuuuy complejo, pero algo en plan:

| Característica | MUSES | IBM | Sophos | Samsung Knox |
| --- | --- | --- | --- | --- |
| **Licencia** | `Libre` | `Propietaria` | `Propietaria` | `Propietaria` |
| **Dispositivos** | `Smartphone, tables, pc y netbooks` | `Lo que sea` | `Lo que sea` | `Lo que sea` |
| _Precio_ | `Sin licencia` | `Lo que sea` | `Lo que sea` | `Lo que sea` |
| _Ventajas_ | `Sin licencia` | `Lo que sea` | `Lo que sea` | `Lo que sea` |
| _Desventajas_ | `Sin licencia` | `Lo que sea` | `Lo que sea` | `Lo que sea` |

**Comment by unintendedbear** [comment]
Me parece una buena idea :)

**Comment by unintendedbear** [comment]
Ehm, no me va a dar tiempo a hacer la tabla :/ pensaba que lo decías porque lo ibas a incluir. Si no quiere hacerlo nadie y no me da tiempo, se queda así como estaba ://

**Comment by JJ** [comment]
Yo cierro por hoy. Queda responder a varias cuestiones de los revisores.

**Comment by unintendedbear** [comment]
Vale, gracias por contribuir! Yo me ocupo del resto hasta dejarlo listo.

**Comment by pacastillo** [comment]
Hola, Paloma,
si quieres añadir la tabla, te paso alguna información que te puede servir.

Para KNOX Premium:
     https://www.samsungknox.com/es/products/compare-features
precio = $1 al mes por dispositivo
dispositivos = Samsung, iOS, Android
Enfocado a Empresas, Pequeñas y medianas empresas (pymes), Organismos gubernamentales
Ventajas = Soporte técnico; Integración con Active Directory; Gestión de aplicaciones (listas blancas y negras)
Desventajas = privativo; coste de las licencias

Sophos tiene muchos productos:
    http://www.sophos.com/es-es/products.aspx
Concretamente el Mobile Control puede ser el más cercano para comparar:
   http://www.sophos.com/es-es/products/mobile-control.aspx
Dispositivos=  iOS, Android (incluido Samsung SAFE), Windows Phone 8
Precio= solicitar presupuesto
Ventajas= gestionar innumerables dispositivos con un solo producto; Administración de aplicaciones móviles con Enterprise App Store; protección de de contenidos en móviles; Controla el acceso al correo electrónico a través de una puerta de enlace de correo electrónico segura
Desventajas = privativo; coste de las licencias (no especificadas en la web)

**Comment by pacastillo** [comment]
Otra herramienta que podría añadirse en la sección "Tools for corporate mobile security" es "SonicWall Mobile Connect"
    http://alternativeto.net/software/sonicwall-mobile-connect/

SonicWALL® Mobile Connect™ provides users full network-level access to corporate and academic resources over encrypted SSL VPN connections. The client provides anytime, anywhere access to critical applications such as email, virtual desktop sessions and other iOS applications.

Parece que es una aplicación libre, pero requiere que tengas una licencia de otro producto (SonicWALL Aventail E-Class Secure Remote Access (SRA) appliances running 10.5.4 or higher, SonicWALL SRA appliances running 5.5 or higher, SonicWALL Next-Generation Firewall).

Quizás en la subsecc. de otras herramientas...

**Comment by deantares** [comment]
Esto yo, me lo autoasigno.

**Comment by unintendedbear** [comment]
Gracias :_______________

**Comment by deantares** [comment]
Os pongo la tabla tal y como la tengo (no la puedo añadir al paper porque no estoy en el PC adecuado). Quedan cosas por comentar, pero la verdad es que no tengo mucha más idea de que poner. Voy a hacer unas gestiones, ahora cuando vuelva aviso.

`````` \begin{table}[h]
\begin{tabular}{cllllll}
\hline
\multicolumn{1}{|c|}{\textbf{Feature}}                            & \multicolumn{1}{c|}{\textbf{Muses}} & \multicolumn{1}{c|}{\textbf{\begin{tabular}[c]{@{}c@{}}IBM\\ Mobile\\ Security\end{tabular}}} & \multicolumn{1}{c|}{\textbf{\begin{tabular}[c]{@{}c@{}}Sophos\\ Mobile\\ Control\end{tabular}}} & \multicolumn{1}{c|}{\textbf{\begin{tabular}[c]{@{}c@{}}Samsung Knox\\ and\\ Blackberry Balance\end{tabular}}} & \multicolumn{1}{c|}{\textbf{Blackphone}}                             & \multicolumn{1}{c|}{\textbf{\begin{tabular}[c]{@{}c@{}}Android\\ for\\ Work\end{tabular}}}                       \\ \hline
License                                                           & Open Source                         & Propietary                                                                                    & Propietary                                                                                      & Propietary                                                                                                    & Propietary                                                           & Propietary                                                                                                       \\
\begin{tabular}[c]{@{}c@{}}Devices\\ \&\\ Plataforms\end{tabular} &                                     &                                                                                               & \begin{tabular}[c]{@{}l@{}}IOS, Android\\ and Windows Phone 8\end{tabular}                      & \begin{tabular}[c]{@{}l@{}}Android Samsung devices\\ and IOS\end{tabular}                                     & Own device                                                           & \begin{tabular}[c]{@{}l@{}}Android and\\ Devices with \\ Chrome Browser\end{tabular}                             \\
Price                                                             & Free*                               &                                                                                               & By request                                                                                      & 12\$ per year/device                                                                                          & \begin{tabular}[c]{@{}l@{}}120\$ per \\ year **\end{tabular}         & \begin{tabular}[c]{@{}l@{}}$50 per user per month\\ $12 per user per month\\ with inlimited storage\end{tabular} \\
Strengths                                                         &                                     &                                                                                               & \begin{tabular}[c]{@{}l@{}}Can manage countless\\ devices with one solution\end{tabular}        &                                                                                                               &                                                                      & \begin{tabular}[c]{@{}l@{}}Cloud based\\ Integrated in Google for Work\end{tabular}                              \\
Handicap                                                          &                                     &                                                                                               &                                                                                                 &                                                                                                               & \begin{tabular}[c]{@{}l@{}}Only to their\\ own devices.\end{tabular} &                                                                                                                  \\
\multicolumn{7}{l}{\begin{tabular}[c]{@{}l@{}}* Requires own hardware\\ \\ ** By purchasing the terminal tree one-year subscriptions are archieved.\end{tabular}}                                                                                                                                                                                                                                                                                                                                                                                                                                                  
\end{tabular}
\end{table}```
``````

**Comment by amorag** [comment]
Antares, llevo media hora con la tabla, primero corrigiendo errorcillos que no permitían compilarla y ahora intentando ubicarla porque es demasiado grande.

Además, hay varias columnas vacías que habría que rellenar para que fuera útil…

Yo podría rellenar las de MUSES, pero no las demás.

La dejamos para la versión definitiva. ;D

Gracias en todo caso.

De: Antonio Fernández Ares [mailto:notifications@github.com] 
Enviado el: jueves, 16 de abril de 2015 21:10
Para: geneura-papers/2014-2015-COMCOM-MUSES_vs_SotA_BYOD_Systems
Asunto: Re: [2014-2015-COMCOM-MUSES_vs_SotA_BYOD_Systems] Tabla Comparativa final (#20)

Os pongo la tabla tal y como la tengo (no la puedo añadir al paper porque no estoy en el PC adecuado). Quedan cosas por comentar, pero la verdad es que no tengo mucha más idea de que poner. Voy a hacer unas gestiones, ahora cuando vuelva aviso.

\begin{tabular}{cllllll}
\hline
\multicolumn{1}{|c|}{\textbf{Feature}}                            & \multicolumn{1}{c|}{\textbf{Muses}} & \multicolumn{1}{c|}{\textbf{\begin{tabular}[c]{@{}c@{}}IBM\ Mobile\ Security\end{tabular}}} & \multicolumn{1}{c|}{\textbf{\begin{tabular}[c]{@{}c@{}}Sophos\ Mobile\ Control\end{tabular}}} & \multicolumn{1}{c|}{\textbf{\begin{tabular}[c]{@{}c@{}}Samsung Knox\ and\ Blackberry Balance\end{tabular}}} & \multicolumn{1}{c|}{\textbf{Blackphone}}                             & \multicolumn{1}{c|}{\textbf{\begin{tabular}[c]{@{}c@{}}Android\ for\ Work\end{tabular}}}                       \ \hline
License                                                           & Open Source                         & Propietary                                                                                    & Propietary                                                                                      & Propietary                                                                                                    & Propietary                                                           & Propietary                                                                                                       \
\begin{tabular}[c]{@{}c@{}}Devices\ &\ Plataforms\end{tabular} &                                     &                                                                                               & \begin{tabular}[c]{@{}l@{}}IOS, Android\ and Windows Phone 8\end{tabular}                      & \begin{tabular}[c]{@{}l@{}}Android Samsung devices\ and IOS\end{tabular}                                     & Own device                                                           & \begin{tabular}[c]{@{}l@{}}Android and\ Devices with \ Chrome Browser\end{tabular}                             \
Price                                                             & Free\*                               &                                                                                               & By request                                                                                      & 12\$ per year/device                                                                                          & \begin{tabular}[c]{@{}l@{}}120\$ per \ year *_\end{tabular}         & \begin{tabular}[c]{@{}l@{}}$50 per user per month\ $12 per user per month\ with inlimited storage\end{tabular} \
Strengths                                                         &                                     &                                                                                               & \begin{tabular}[c]{@{}l@{}}Can manage countless\ devices with one solution\end{tabular}        &                                                                                                               &                                                                      & \begin{tabular}[c]{@{}l@{}}Cloud based\ Integrated in Google for Work\end{tabular}                              \
Handicap                                                          &                                     &                                                                                               &                                                                                                 &                                                                                                               & \begin{tabular}[c]{@{}l@{}}Only to their\ own devices.\end{tabular} &                                                                                                                  \
\multicolumn{7}{l}{\begin{tabular}[c]{@{}l@{}}_ Requires own hardware\ \ *\* By purchasing the terminal tree one-year subscriptions are archieved.\end{tabular}}  
\end{tabular}
\end{table}```

—
Reply to this email directly or view it on GitHub https://github.com/geneura-papers/2014-2015-COMCOM-MUSES_vs_SotA_BYOD_Systems/issues/20#issuecomment-93817787 .  https://github.com/notifications/beacon/AC6-WuHXG5K0OVxZ1Cjg0w33HHFYZb6yks5oAACfgaJpZM4ECGzY.gif 

No se encontraron virus en este mensaje.
Comprobado por AVG - www.avg.com
Versión: 2015.0.5863 / Base de datos de virus: 4331/9551 - Fecha de publicación: 04/16/15

---

No se encontraron virus en este mensaje.
Comprobado por AVG - www.avg.com
Versión: 2015.0.5863 / Base de datos de virus: 4331/9551 - Fecha de publicación: 04/16/15

**Comment by JJ** [comment]
¿Se mete la tabla en esta versión?

**Comment by JJ** [comment]
Sería conveniente que contestárais a esto, reasignárais, o lo que fuera.

**Comment by unintendedbear** [comment]
Hola,

He leído en los comentarios de los revisores que sí, que estaría bien que la pusiéramos. Lo que ya no sé es si voy a cambiar la sección 3, porque otra de las sugerencias es poner las herramientas de otra manera:

"Considering variety of BYOD tools and their different features, authors might consider to introduce or reuse a taxonomy or classification of those approaches, and state the place of MUSES there (or define a new subcategory, if deemed necessary)"

¿Cómo lo veis?

**Comment by fergunet** [comment]
Creo que sí, hay que poner una taxonomía (inventárnosla) para clasificar
las herramientas y poner varias columnas en esa tabla con el tipo de
solución que es. En principio se me ocurre como taxonomía:
- Relativo al aprendizaje para detectar amenazas: online/offline (por
  ejemplo, muses es online)
- Relativo a la base de datos de información: fija/variable o actualizable
  (muses es variable)
- Relativo al control o acceso de los datos: invasivo/no invasivo (muses es
  no invasivo)
- Relativo al control del sistema: superusuario/no superusuario

Cosas así. Describir cada una con un párrafo y luego usarla para clasificar
las herramientas. Luego le decimos al revisor "Hemos propuesto de paso una
taxonomía que te cagas"

Id pensando más cosas de la taxonomía y la ponemos aquí.

2015-06-16 20:11 GMT+02:00 Paloma de las Cuevas Delgado <
notifications@github.com>:

> Hola,
> 
> He leído en los comentarios de los revisores que sí, que estaría bien que
> la pusiéramos. Lo que ya no sé es si voy a cambiar la sección 3, porque
> otra de las sugerencias es poner las herramientas de otra manera:
> 
> "Considering variety of BYOD tools and their different features, authors
> might consider to introduce or reuse a taxonomy or classification of those
> approaches, and state the place of MUSES there (or define a new
> subcategory, if deemed necessary)"
> 
> ¿Cómo lo veis?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/geneura-papers/2014-2015-COMCOM-MUSES_vs_SotA_BYOD_Systems/issues/20#issuecomment-112517767
> .

## 

Dr. Pablo García Sánchez
University of Granada
http://www.ugr.es/~pablogarcia

**Comment by amorag** [comment]
A mí me gustó lo de la tabla en su momento, pero no la metí porque estaba un poco incompleta.
Y eso que me tiré 30 minutos ajustándola porque me fallaba al compilar. :_(

@deantares porfa, hazla de nuevo pero más completa, ahora que hay tiempo.

Yo sí voto por cambiar un poco la sección 3, siguiendo los comentarios de los revisores.

Lo de la taxonomía también estaría bien, pero hay que pensar una que sea interesante desde el punto de vista de este este artículo. ;)

**Comment by deantares** [comment]
Estoy a ver como consigo meter la tabla tan grande en una página tan pequeña... Desde luego, es la historia de mi vida :sweat_smile:

**Comment by unintendedbear** [comment]
Ea, pero ¿no es mejor que la rediseñemos? Me parece bien lo de clasificar las herramientas, quiero ver si rediseño la sección 3. Es que así lo mismo las dos cosas nos ocupan mucho menos ¿no?

**Comment by pacastillo** [comment]
¿no se puede poner una tabla ocupando la página completa, en apaisado?

**Comment by deantares** [comment]
Ahora os pongo lo que estoy haciendo, que le ha gustado a @fergunet y @amorag

**Comment by deantares** [comment]
Una vista previa de como queda la tabla:

![seleccion_158](https://cloud.githubusercontent.com/assets/1782996/8210821/0fd588dc-1514-11e5-8379-8176103283bf.png)

Hemos pensado que en lugar de poner una tabla enorme, es mejor poner varias tablas pequeñitas: una con el precio-licencia, otra con las taxonomías, otras con las ventajas-desventajas,...

Pongo unos pequeños tex en el repositorio, con las tablas para añadiarlas ahora al artículo en donde consideréis que queda mejor :smile:

**Comment by pacastillo** [comment]
¿qué columnas recogería cada una de ellas?

**Comment by deantares** [comment]
Pues si se hace lo de la taxonomías de Pablo:
- Relativo al aprendizaje para detectar amenazas: online/offline (por
  ejemplo, muses es online)
- Relativo a la base de datos de información: fija/variable o actualizable
  (muses es variable)
- Relativo al control o acceso de los datos: invasivo/no invasivo (muses es
  no invasivo)
- Relativo al control del sistema: superusuario/no superusuario

**Comment by unintendedbear** [comment]
Me parece óptimo lo que dicen @deantares y @fergunet, aunque vamos a hacer brainstorming luego pero me parece una buena taxonomía. Lo que no sé es si veis bien reestructurar la sección en base a eso o dejarla así, con las herramientas una a una, y además agregar un par de párrafos con esto. Pero es que como sigamos así, nos vamos a las 35 páginas :\

**Comment by fergunet** [comment]
Si no hay límite de espacio propongo lo de la taxonomía, que además les damos a los reviewers una razón justificando el paper. Debería ser antes de presentar las soluciones, y comentar en cada una en qué parte encaja (además de las tablas). Si queréis escribo yo la taxonomía en inglés (podéis asignarme un issue).

¿Cuando es el deadline, @unintendedbear @amorag?

**Comment by amorag** [comment]
La fecha límite para la revisión es el 6 de julio.

En principio no hay límite de páginas.

De: Pablo García Sánchez [mailto:notifications@github.com] 
Enviado el: jueves, 18 de junio de 2015 18:21
Para: geneura-papers/2014-2015-COMCOM-MUSES_vs_SotA_BYOD_Systems
CC: Antonio Mora
Asunto: Re: [2014-2015-COMCOM-MUSES_vs_SotA_BYOD_Systems] Tabla Comparativa final (#20)

Si no hay límite de espacio propongo lo de la taxonomía, que además les damos a los reviewers una razón justificando el paper. Debería ser antes de presentar las soluciones, y comentar en cada una en qué parte encaja (además de las tablas). Si queréis escribo yo la taxonomía en inglés (podéis asignarme un issue).

¿Cuando es el deadline, @unintendedbear https://github.com/unintendedbear  @amorag https://github.com/amorag ?

—
Reply to this email directly or view it on GitHub https://github.com/geneura-papers/2014-2015-COMCOM-MUSES_vs_SotA_BYOD_Systems/issues/20#issuecomment-113207351 .  https://github.com/notifications/beacon/AC6-WhcL9MAhS_CwBwPak661asWaqNPHks5oUudQgaJpZM4ECGzY.gif 

No se encontraron virus en este mensaje.
Comprobado por AVG - www.avg.com
Versión: 2015.0.6030 / Base de datos de virus: 4365/10043 - Fecha de publicación: 06/18/15

---

No se encontraron virus en este mensaje.
Comprobado por AVG - www.avg.com
Versión: 2015.0.5961 / Base de datos de virus: 4355/9987 - Fecha de publicación: 06/10/15
Base de datos de virus interno no está actualizado.

**Comment by JJ** [comment]
Si se ha incorporado en otro issue, por favor, cerradlo.
