### ISSUE TITLE
Highlight new results in the paper

### ISSUE THREAD

**Issue by JJ** [geneura-papers/2014-2015-COMCOM-MUSES_vs_SotA_BYOD_Systems#22]
References to previous published papers and what's the difference from them.

**Comment by unintendedbear** [comment]
In which section should this be included exactly? Conclusions or Introduction?

**Comment by pacastillo** [comment]
introduction

**Comment by amorag** [comment]
A este respecto yo diría que se incluyesen más detalles de lo que se ha implementado en los últimos meses desde que enviamos el artículo, quizá se puedan meter cosas del Deliverable 5.3, que ahondaba en la descripción del KRS, con los módulos que se planeaba que lo formasen.

O detalles más concretos (y más realistas) de cómo ha cambiado el sistema en estas últimos meses.

Si podemos meter nuevo contenido en el artículo (una nueva sección, o subsección, por ejemplo), que no estará previemente publicado será un buen golpe de efecto para que lo acepten. ;)

¿Qué opináis?

**Comment by JJ** [comment]
Pues que lo hagas.

**Comment by amorag** [comment]
Pero yo no sé lo que hay en el sistema actualmente, sólo lo que se planteó.

@unintendedbear, ¿meto en el artículo el esquema que describimos en el D5.3 completo?
¿Hasta qué punto de ese esquema incluyo?¿Data Miner?¿Algo del Knowlegde Compiler?

Gracias.

**Comment by unintendedbear** [comment]
Está la lista de tasks en la wiki, y los mails y las telcos. Pero vaya de todas maneras no pasa nada porque este issue lo tengo asignado yo, no te preocupes, gracias! El 5.3 además es de principios de año.
