### ISSUE TITLE
Comment on a priori enforcement

### ISSUE THREAD

**Issue by JJ** [geneura-papers/2014-2015-COMCOM-MUSES_vs_SotA_BYOD_Systems#23]
Explain that it's done using default security policies.

**Comment by unintendedbear** [comment]
Note-to-self -> Include this at the end of p.11:

"As a summary, this application includes two modules: a controller and an actuator. The first one  monitors the environment (context) and the users’ behaviour, translating their actions in a sequence of events. These events, along with the patterns defining the user’s conduct, are processed by the system in real-time by means of a Risk and Trust Analysis Engine (RT2AE) and an Event Correlation module. Then, a decision is taken in the corporate Security Operations Centre (SOC) side, considering the RT2AE output and **the set of security rules** adapted to that specific user and context."

It is indeed commented, but I guess it should be highlighted or, at least, give more importance to it.

**Comment by amorag** [comment]
En mi opinión, lo que el revisor indica:

"The tools aims at enforcing security policies, however the security response occurs only AFTER a particular pattern is recognized to be potentially malicious. From my understandings, there is no a-priori enforcement except for the prediction based on event logs. This could mean that e security violation could in principle happen and only later recognized. This is not so suitable for a corporate environment with strict security requirements. This statement should be discussed and preferably discredited with experimental results."

No ha sido explicado o justificado completamente en el paper. 
En él se dice que el cliente actúa como mecanismo de tratamiento anticipado ('a-priori') de posibles violaciones de seguridad, pero lo que remarca el revisor es que MUSES quizá debería hacer una mejora del conjunto de reglas sin necesitar un gran conjunto de eventos sucedidos (o incluso sin necesitar que hayan ocurrido eventos de violaciones de seguridad).

Lo que habría que aclarar es que las reglas inicialmente las debe definir el CSO para tratar con el mayor número de violaciones de seguridad posible. MUSES no puede generar reglas para tratar con incidentes que no hayan sucedido nunca, máxime si no se parecen a otros. Deben estar tipificados para poder generar o inferir reglas que los traten.

Lo que sí puede hacer MUSES es determinar que un patrón se parece a otro y que la decisión asociada al mismo sería la misma. Si un patrón se parece a uno que haya desembocado en una violación de seguridad, idealmente, ese patrón inferirá una decisión 'DENY', pero así la debería tener el patrón original del incidente, lo que significaría que dicho incidente no debería haber ocurrido... en fin, es un poco lío.

Por otra parte, MUSES ofrecerá (u ofrecería) herramientas para que el CSO pueda detectar comportamientos anómalos en los usuarios, por ejemplo (aquello del clustering y visualización de patrones con SOM y demás), de modo que ese usuario podría analizar esos comportamientos y definir reglas que anticipen una posible violación de seguridad.

Vamos, habría que dejar claro que MUSES no es un sistema independiente del usuario, que no viene a sustituir a un CSO, y que no puede 'crear cosas' si no las 'ha visto' antes. 

Eso sí, MUSES realizará una mejora/optimización de reglas basada en otros factores, que permitan simplificar el conjunto (reglas redundantes o superflúas) o mejorar algunas reglas (reducir sus términos, por ejemplo). Esto podrá repercutir en una detección más precisa de dichos incidentes.
Pero en mi opinión, MUSES no podrá tratar incidentes nuevos.

Todo esto habría que ponerlo bonico para el revisor, destacando lo que MUSES sí puede hacer y justificando lo que no pueda hacer.

**Comment by pacastillo** [comment]
Hay que aclararle al revisor que el sistema no es un antivirus ni un cortafuegos. 
Con diversa información se pueden mejorar la reglas iniciales (las del CSO; quizás se pueda hacer ahí un símil a las reglas del iptables... no sé). 
Además, esas reglas mejorarán la defensa en otros dispositivos de otras personas de forma automática.

**Comment by unintendedbear** [comment]
Sí, lo de que no es un antivirus lo incluí porque no quedaba claro, además especifiqué que, por ejemplo, MUSES sí que mira si hay un antivirus instalado o no, y si es que no pues se queja.
El ejemplo de las iptables lo puso Fergu en la taxonomía, pero lo mismo conviene mencionarlo de nuevo en el párrafo del a priori, ¿cómo lo veis?

**Comment by amorag** [comment]
En mi opinión, se puede poner una breve referencia a lo de iptables, pero insito en dejarle muy claro en el texto y, sobre todo, en la respuesta, lo que he comentado arriba, porque creo que aclararía al revisor algunas cosas sobre cómo funciona MUSES y por qué tiene la supuesta limitación que comenta.
