### ISSUE TITLE
Discuss the possibility of compromised sensors

### ISSUE THREAD

**Issue by JJ** [geneura-papers/2014-2015-COMCOM-MUSES_vs_SotA_BYOD_Systems#25]
is this possible? Can a rootkit do something with them? Maybe discuss in a telco?

**Comment by JJ** [comment]
Antonio, esto tiene cinco días. Por favor, revísalo.

**Comment by amorag** [comment]
No tengo ni idea de esto. Lo miraré.

Perdona, pero no ví los milestones, estoy corrigiendo prácticas y apagando fuegos a saco.

**Comment by pacastillo** [comment]
¿un rootkit para qué cosa?

**Comment by unintendedbear** [comment]
Pues supongo que para evitar que los sensores manden medidas al servidor. O las envíen falseadas. Esto último no sé si es posible, supongo que sí. A ver que opinen los security boys xD @jlmacal @gstvrmrlpz 

De todas maneras, si me confirmáis que los rootkit estos hagan eso, puedo encargarme yo de explicar esto cuando acabe con mis issues.

**Comment by pacastillo** [comment]
Los sensores, en función de qué tipo de sistema operativo lleven, pueden ser comprometidos. Pero si se trata de "motas" sencillas (zigbee o un arduino), el problema de un ataque puede producirse más bien porque un atacante haga un "man in the middle" e intercepte las comunicaciones.

**Comment by unintendedbear** [comment]
Vale, pues entonces al ser smartphones, tablets y portátiles (Android, iOS y Windows), solo nos tenemos que preocupar de ¿qué exactamente? Porque por ejemplo si el teléfono está rooteado se detecta. Si tiene un rootkit instalado y no se mandan estadísticas de los sensores también se detecta.

**Comment by gstvrmrlpz** [comment]
teoricamente con un rootkit puedes modificar el binario para que haga lo que quieras...

**Comment by jlmacal** [comment]
Y ya de paso probar si cuela alguna remote comman execution y 
comprometer el servidor desde el cliente...

**Comment by unintendedbear** [comment]
Jajajajaja, bien, pues eso no se contempla. Vivan las cosas bien desarrolladas. De modo que ¿hay alguna manera de ponerlo bonito con lo que dije que sí se detecta y evitar dejar al descubierto lo mal implementado que está? Y a lo mejor poner que el resto de cosas se implementarán en futuras versiones (?) O no, eso es tirarnos piedras también, me temo.

**Comment by jlmacal** [comment]
Vale, forma elegante de esquivar situaciones como la que comentas.

1 Cualquier proceso es susceptible de verse afectado por lo que afecta 
al cliente de muses, en el caso de los rootkits. (TODAS PU...)
2 Dado que el servidor y cliente no siguieron una metodología de 
desarrollo seguro (y es algo sumamente normal, no es software militar :) 
), la seguridad deriva del sistema que lo hospeda. (ECHAS EL MARRON A OTRO)
3 Las pruebas de seguridad son continuas, y a lo largo del tiempo de 
vida de la aplicación. Ahora es un prototipo, lo principal es que la 
funcionalidad cumpla lo descrito y detectar problemas de usabilidad. 
(APLAZAS EL MARRON)

Nos vemos!

**Comment by unintendedbear** [comment]
Jajajajaja, muchas gracias @jlmacal :bear:

**Comment by amorag** [comment]
Paloma, si no te importa, haz tú esta descripción, ya que sabes mucho más que yo del tema.

Gracias.
