### ISSUE TITLE
Revise paper structure

### ISSUE THREAD

**Issue by JJ** [geneura-papers/2014-2015-COMCOM-MUSES_vs_SotA_BYOD_Systems#26]
Check it out and suggest how things could be improved.

**Comment by JJ** [comment]
I don't see a major problem with the structure, other that it's not the "traditional" introduction, state of the art, results and conclusions. Maybe we should restructure along those lines, changing 1 and 2 into Intro, 3 would be state of the art, and the rest. What do you think?

**Comment by fergunet** [comment]
It depends what we should sell.
- Is it a paper focused in Muses? Then, the classic paper approach
  (although without results section).
- Is it a survey plus Muses? Then the current structure (but with some
  changes, of course).

2015-06-19 13:38 GMT+02:00 Juan Julián Merelo Guervós <
notifications@github.com>:

> I don't see a major problem with the structure, other that it's not the
> "traditional" introduction, state of the art, results and conclusions.
> Maybe we should restructure along those lines, changing 1 and 2 into Intro,
> 3 would be state of the art, and the rest. What do you think?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/geneura-papers/2014-2015-COMCOM-MUSES_vs_SotA_BYOD_Systems/issues/26#issuecomment-113485286
> .

## 

Dr. Pablo García Sánchez
University of Granada
http://www.ugr.es/~pablogarcia

**Comment by JJ** [comment]
2015-06-19 19:57 GMT+02:00 Pablo García Sánchez notifications@github.com:

> It depends what we should sell.
> - Is it a paper focused in Muses? Then, the classic paper approach
>   (although without results section).
> - Is it a survey plus Muses? Then the current structure (but with some
>   changes, of course).

This is it, I would say.

JJ

**Comment by amorag** [comment]
It is (or should be) the second option.

There are some papers presenting MUSES already. ;)

PD
Ya me habéis liado con el inglés. :_( :D

**Comment by JJ** [comment]
Even if it's based on Muses, the structure should change as per the reviewers request. So what do you suggest?
