### ISSUE TITLE
Improve the state of the art

### ISSUE THREAD

**Issue by JJ** [geneura-papers/2014-2015-COMCOM-MUSES_vs_SotA_BYOD_Systems#27]
Check item number 5 for this reviewer, new papers suggested and incorporate them to the state of the art.

**Comment by JJ** [comment]
Antonio, haz esto o reasigna.

**Comment by amorag** [comment]
Gracias por encargarte Pablo.

Intentaré contribuir a la vuelta en todo lo que pueda.

**Comment by fergunet** [comment]
No está terminado todavía, tengo que meter más papers: otro del revisor, más otros chulos que vaya yo encontrando por ahí, sólo llevo 4 leídos. También hay que justificar por qué MUSES es mejor que esos papers ( @unintendedbear quizás, termina la frasecilla que he dejado a medio escribir ). También confirmadme que donde lo he puesto es buen sitio, que no me sé la estructura del paper aún. Sobre todo @JJ que es el que sabe como hilvanar SOAs (a éste aún le queda hilvanamiento y justificación, soy consciente). También @fergunet, encárgate de contestar al referee cuando termines xD

**Comment by deantares** [comment]
Muy fan de que @fergunet se mande tareas a si mismo. Mándame si quieres alguno de los que tengas sin leer por si mañana en el congreso me aburro.

**Comment by fergunet** [comment]
Busca cualquier artículo de investigación en BYOD (algoritmos y movidas de esas) que veas interesante, los del revisor ya están casi revisados.

**Comment by unintendedbear** [comment]
Lo he movido (estoy en ello, vaya) al final de la sección porque he visto mejor ponerlo después del background en enterprise security. También voy a completar eso que me ha dicho @fergunet.

Ahora bien, estoy pensando que en realidad esta sección 2 estaba porque no había un SotA propiamente dicho. Así que ahora que lo está haciendo Fergu... ¿quitamos lo otro y renombramos la sección a SotA?

Necesito opiniones sobre esto. Si pensáis "es cambiar mucho el paper":
1. lo sé
2. es que el original estaba mal. Muy mal.
3. en cuanto he tenido tiempo me lo he replanteado y estoy encaminándolo, pero claro, esto significa cambiarlo tanto :\

Ya podéis tirarme piedras.

**Comment by fergunet** [comment]
A ver, lo que vendemos es lo siguiente (no están en orden de importancia):
1) Una taxonomía de clasificación de sistemas BYOD
2) Un estado del arte en investigación en BYOD: conceptos preliminares y artículos científicos
3) Un análisis de productos comerciales BYOD y su clasificación en nuestra taxonomía
4) Un nuevo sistema, MUSES, que tiene algunas cosas de la taxonomía que los anteriores no tienen (adaptación, por ejemplo) 

Entonces, el título está bien, pero en el abstract y la intro debemos poner "Tras una presentación de conceptos importantes hacemos un estudio del SOTA en BYOD, y a partir de ahí, se nos ha ocurrido crear una taxonomía, luego presentamos una serie de productos comerciales (taxonomizados) y finalmente, un nuevo sistema guay.

Sobre tu pregunta: la sección 2 se puede quedar como está (Preliminary concepts and background about enterprise security), sólo hacer hincapié en la intro y abstract de lo que aporta este artículo.

**Comment by fergunet** [comment]
Se me ha olvidado cerrar este issue cuando he añadido la taxonomia al abstract, introducción y conclusiones 9fd243bc5963ceb8abd949821900690aa13532ac
