### ISSUE TITLE
Enfocar de otra forma el producto de IBM

### ISSUE THREAD

**Issue by JJ** [geneura-papers/2014-2015-COMCOM-MUSES_vs_SotA_BYOD_Systems#3]
Un revisor dice que parece un panfleto de producto. Para empezar, usar un trabajo publicado tal como este:
http://www-935.ibm.com/services/uk/en/attachments/pdf/Securing_mobile_devices_in_the_business_environment.pdf

También añadido al .bib

**Comment by unintendedbear** [comment]
Yo en serio es que me deprimo intentando defender lo nuestro cuando nos dan cien mil vueltas ya por favor :( http://www-935.ibm.com/services/us/en/it-services/security-services/vulnerability-management/index.html
