### ISSUE TITLE
Provide details on integration options

### ISSUE THREAD

**Issue by JJ** [geneura-papers/2014-2015-COMCOM-MUSES_vs_SotA_BYOD_Systems#33]
On p. 17

**Comment by unintendedbear** [comment]
Is this related to "the authors do not provide at least an indication of the data amount/complexity that is gathered and processed by the system, and at what rate it grows"? Is the only comment I see about p.17

**Comment by unintendedbear** [comment]
I'll answer myself: is about necessary effort to make an app MUSES aware. Working on it, then!

**Comment by unintendedbear** [comment]
Again, plis revisad y cerrad.
