### ISSUE TITLE
How does Muses approaches newly discovered vulnerabilities or threats?

### ISSUE THREAD

**Issue by JJ** [geneura-papers/2014-2015-COMCOM-MUSES_vs_SotA_BYOD_Systems#35]
Explain.

**Comment by JJ** [comment]
Por favor, haz o reasigna.

**Comment by JJ** [comment]
Lo siento, Paloma, te lo reasigno porque no creo que nadie más sepa de esto.

**Comment by amorag** [comment]
Gracias.

Intentaré contribuir en lo que pueda a mi vuelta.

**Comment by unintendedbear** [comment]
Plis alguien que me revise estos cambios y cierre?
