### ISSUE TITLE
Include comparison table

### ISSUE THREAD

**Issue by JJ** [geneura-papers/2014-2015-COMCOM-MUSES_vs_SotA_BYOD_Systems#37]
So that differences are clear.

**Comment by JJ** [comment]
Anybody did this? Can somebody please close the issue if so? And change response to reviewers?

**Comment by amorag** [comment]
Antares porfa, completa la tabla con las demás herramientas analizadas si hay info sobre ellas. ;)

¿Había más tablas o sólo la de las licencias, dispositivos y precios?

¡Gracias!

**Comment by fergunet** [comment]
@JJ the final table is not yet included. @deantares made some tables (they need to be added with \include), but the last one is still required. Reopening.

**Comment by JJ** [comment]
OK, just do it! Deadline is tomorrow.

**Comment by deantares** [comment]
Done. Please add to the main TEX file the content of table*.tex files.
