### ISSUE TITLE
Prepare a response letter that includes changes in the text.

### ISSUE THREAD

**Issue by JJ** [geneura-papers/2014-2015-COMCOM-MUSES_vs_SotA_BYOD_Systems#40]
In the same structure as was done in version 1. No issue will be closed until the concerns raised by the reviewer is addressed in the letter.

**Comment by amorag** [comment]
Una cosa respecto a esto, el revisor número 3 (el segundo que ha revisado) parece que es nuevo en el proceso.

Por lo que pienso que alguna de las cuestiones que plantea se pueden responder tomando como base parte de otras respuestas de la primera revisión.

Ayudaré a completar las respuestas a mi vuelta, si es necesario.

Un saludo.
