### ISSUE TITLE
Prepare response to reviewers

### ISSUE THREAD

**Issue by JJ** [geneura-papers/2014-2015-COMCOM-MUSES_vs_SotA_BYOD_Systems#42]
Prepare letter with response to reviewers.

**Comment by amorag** [comment]
Yo empezaré esto.
Luego lo reasigno. ;)

**Comment by JJ** [comment]
Ya lo estoy haciendo yo, Antonio.

2015-06-19 12:09 GMT+02:00 Antonio Mora notifications@github.com:

> Yo empezaré esto.
> Luego lo reasigno. ;)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/geneura-papers/2014-2015-COMCOM-MUSES_vs_SotA_BYOD_Systems/issues/42#issuecomment-113459650
> .

## 

JJ

**Comment by amorag** [comment]
Ok, hazlo tú entonces y yo luego voy aportando. ;)

Como no tenía nadie asignado…

De: Juan Julián Merelo Guervós [mailto:notifications@github.com] 
Enviado el: viernes, 19 de junio de 2015 12:12
Para: geneura-papers/2014-2015-COMCOM-MUSES_vs_SotA_BYOD_Systems
CC: Antonio Mora
Asunto: Re: [2014-2015-COMCOM-MUSES_vs_SotA_BYOD_Systems] Prepare response to reviewers (#42)

Ya lo estoy haciendo yo, Antonio.

2015-06-19 12:09 GMT+02:00 Antonio Mora notifications@github.com:

> Yo empezaré esto.
> Luego lo reasigno. ;)
> 
> —
> Reply to this email directly or view it on GitHub
> < https://github.com/geneura-papers/2014-2015-COMCOM-MUSES_vs_SotA_BYOD_Systems/issues/42#issuecomment-113459650 https://github.com/geneura-papers/2014-2015-COMCOM-MUSES_vs_SotA_BYOD_Systems/issues/42#issuecomment-113459650>
> .

## 

JJ

—
Reply to this email directly or view it on GitHub https://github.com/geneura-papers/2014-2015-COMCOM-MUSES_vs_SotA_BYOD_Systems/issues/42#issuecomment-113459996 .  https://github.com/notifications/beacon/AC6-WmkWzYfw04Lz8Q8mZX89GoKQxsMQks5oU-J9gaJpZM4FHBVO.gif 

No se encontraron virus en este mensaje.
Comprobado por AVG - www.avg.com
Versión: 2015.0.6030 / Base de datos de virus: 4365/10051 - Fecha de publicación: 06/19/15

---

No se encontraron virus en este mensaje.
Comprobado por AVG - www.avg.com
Versión: 2015.0.5961 / Base de datos de virus: 4355/9987 - Fecha de publicación: 06/10/15
Base de datos de virus interno no está actualizado.
