### ISSUE TITLE
Address .bib errors

### ISSUE THREAD

**Issue by JJ** [geneura-papers/2014-2015-COMCOM-MUSES_vs_SotA_BYOD_Systems#43]
```
Warning--empty title in Adams_Users05
Warning--empty booktitle in android11
Warning--empty journal in viega2005use
Warning--empty journal in hildenbrand2014
Warning--there's a number but no series in classification_67
```

Please check .bib file and fix these errors. Prefarably whoever included them, @unintendedbear or @amorag or @fergunet

**Comment by JJ** [comment]
Antonio, ¿puedes mirar esto, por favor?

**Comment by amorag** [comment]
Sí, hoy me pongo con los issues en el avión. ;)

De: Juan Julián Merelo Guervós [mailto:notifications@github.com] 
Enviado el: martes, 23 de junio de 2015 8:28
Para: geneura-papers/2014-2015-COMCOM-MUSES_vs_SotA_BYOD_Systems
CC: Antonio Mora
Asunto: Re: [2014-2015-COMCOM-MUSES_vs_SotA_BYOD_Systems] Address .bib errors (#43)

Antonio, ¿puedes mirar esto, por favor?

—
Reply to this email directly or view it on GitHub https://github.com/geneura-papers/2014-2015-COMCOM-MUSES_vs_SotA_BYOD_Systems/issues/43#issuecomment-114376381 .  https://github.com/notifications/beacon/AC6-WufL7LHijdMOlrftPxhmIYUmaWJSks5oWPPugaJpZM4FHHFS.gif 

No se encontraron virus en este mensaje.
Comprobado por AVG - www.avg.com
Versión: 2015.0.6030 / Base de datos de virus: 4365/10079 - Fecha de publicación: 06/22/15

---

No se encontraron virus en este mensaje.
Comprobado por AVG - www.avg.com
Versión: 2015.0.5961 / Base de datos de virus: 4355/9987 - Fecha de publicación: 06/10/15
Base de datos de virus interno no está actualizado.
