### ISSUE TITLE
Avoid parentheses pt. II

### ISSUE THREAD

**Issue by unintendedbear** [geneura-papers/2014-2015-COMCOM-MUSES_vs_SotA_BYOD_Systems#46]
Reviewers have stated to avoid parantheses as much as possible.

I'm now reviewing the response we're writing for them and I've already found a lot of them.

Please, rewrite.
Thanks.

**Comment by pacastillo** [comment]
I have made some changes to the response letter and I have removed some parentheses  ;)

**Comment by JJ** [comment]
Parentheses have to be suppressed in the text only.  Además, algunos paréntesis son citas del texto, así que...

**Comment by unintendedbear** [comment]
No me refería a que fuera por obligación, ya sé que la obligación es corregirlo en el texto. Tampoco me refiero a citas, acrónimos, o cosas por el estilo. Me refiero a que en general se tiende a hacer esto y me encuentro un montón de frases como:

"However, MUSES presents a limitation regarding the enhancement of rules, since, in principle, it cannot predict (generate rules for dealing with) unexpected or unknown events which could lead to a security incident."

Que no son legibles para nada. Empezar a leer e ir atascándose por cosas así resta interés a la lectura, al hacerla difícil y poco entendible.

**Comment by unintendedbear** [comment]
Es más, veo por tu commit y los de Pedro que sí que se entendía el propósito del issue...

**Comment by JJ** [comment]
Sí, claro. Es más legible, tienes razón. El problema es que los que quedan ahora son o de los revisores o citas literales del texto. Por eso lo he cerrado.

**Comment by unintendedbear** [comment]
Ok, perdona y gracias.
