### ISSUE TITLE
Incluir todas las herramientas comentadas en la comparativa

### ISSUE THREAD

**Issue by amorag** [geneura-papers/2014-2015-COMCOM-MUSES_vs_SotA_BYOD_Systems#47]
Al menos un comentario breve sobre cada una, si no las metemos en la tabla.

Un revisor lo pedía explícitamente, respecto a las de IBM y a WSO2.

¡Gracias!

**Comment by amorag** [comment]
Por ejemplo, puedes coger partes de texto de la sección 3 en la que comparas algunas herramientas de IBM con MUSES y trasladarlas (y enlazarlas) a la Sección 5. ;)

**Comment by amorag** [comment]
En general, los párrafos finales de cada apartado de la sección 3 se podrían mover a la sección 5 y enlazarlos. Así la 3 sería sólo descripción de las herramientas y la 5 comparativa con MUSES.

¿Podéis mirarlo @unintendedbear?

**Comment by unintendedbear** [comment]
No :\ No puedo, no paro ni 5 minutos con el campus y tengo telco a las 15. Por favor, si alguien puede helpear con esto, que lo haga.

**Comment by amorag** [comment]
Bueno, no tiene que ser ahora.

A ver si a lo largo de la tarde es posible.
O si Fergu puede echar una mano.

**Comment by fergunet** [comment]
Pregunta: por qué esas herramientas no tienen su propia sección, como las de antes?

**Comment by unintendedbear** [comment]
Sacto. Les hemos dado menos importancia poniéndolas ahí y ahora no podemos coger y extenderlas como las demás...
BTW ahora incluyo lo de por qué estas y no otras

**Comment by amorag** [comment]
Porque ha sido un error que hemos arrastrado.
En la primera versión teníamos mucho menos contenido de esas herramientas que de las demás, de modo que, para no poner secciones de un párrafo se agruparon todas.

Ahora que tenemos más contenido se podrían separar.

**Comment by amorag** [comment]
En cualquier caso, por favor, lo que hagáis a este respecto o lo de la justificación de por qué se han elegido estas herramientas y no otras ponedlo también en las respuestas.

Gracias.

**Comment by amorag** [comment]
¿Se podrían separar?¿Implicaría muchos cambios?

La verdad es que quedaría mejor, así nos pueden decir algo los revisores.
Pero si al hacerlo hay que añadir más contenido además, entonces no.

**Comment by unintendedbear** [comment]
Yo añadí un poco al de WSo2 porque lo pedían, y al Worx. Pero de verdad que a estas horas, el día que se envía... ya no.

**Comment by pacastillo** [comment]
Creo que mejor dejarlo así, no vayamos a cometer algún error al hacer alguna modificación más grande...
