### ISSUE TITLE
Enganchar bien las secciones

### ISSUE THREAD

**Issue by JJ** [geneura-papers/2014-2015-COMCOM-MUSES_vs_SotA_BYOD_Systems#5]
La sección 2 hace énfasis en la importancia de una ISP. La 3º no la menciona. ¿Hablamos de herramientas que sirven para crear/elaborar/refinar ISPs?

**Comment by unintendedbear** [comment]
¿Qué límite de páginas hay? Hay 24 ahora mismo :$

**Comment by amorag** [comment]
El límite ‘teórico’ son 14 páginas, pero eso es en el formato final, que es diferente (va a doble columna y con un tamaño de letra menor).

Ahora mismo no te preocupes por eso.

Si lo aceptan ya lo reduciremos si es necesario.

De: Paloma de las Cuevas Delgado [mailto:notifications@github.com] 
Enviado el: miércoles, 15 de abril de 2015 11:43
Para: geneura-papers/2014-2015-COMCOM-MUSES_vs_SotA_BYOD_Systems
CC: Antonio Mora
Asunto: Re: [2014-2015-COMCOM-MUSES_vs_SotA_BYOD_Systems] Enganchar bien las secciones (#5)

¿Qué límite de páginas hay? Hay 24 ahora mismo :$

—
Reply to this email directly or view it on GitHub https://github.com/geneura-papers/2014-2015-COMCOM-MUSES_vs_SotA_BYOD_Systems/issues/5#issuecomment-93287102 .  https://github.com/notifications/beacon/AC6-WvIM4DlZ3rtR10EExWoMBPPKAvgRks5n_iougaJpZM4DzSzT.gif 

No se encontraron virus en este mensaje.
Comprobado por AVG - www.avg.com
Versión: 2015.0.5863 / Base de datos de virus: 4331/9542 - Fecha de publicación: 04/15/15

---

No se encontraron virus en este mensaje.
Comprobado por AVG - www.avg.com
Versión: 2015.0.5863 / Base de datos de virus: 4331/9534 - Fecha de publicación: 04/14/15

**Comment by unintendedbear** [comment]
Uhm, no lo veo bien, porque normalmente trabajamos directamente con el formato que se envía, o ¿es que para esta revista no es así? Además, si nos ajustamos al lo que piden, ya lo hemos hecho bien y no hay que re-revisar-re-escribir-re-resumir... vaya, el doble de trabajo.

**Comment by amorag** [comment]
El formato de envío es distinto del formato final en muchas de revistas.

Sobre todo en las de Elsevier.

Además, los números especiales no suelen ser estrictos con el tamaño.

Ya en la primera versión nos pasamos del mismo porque no se tiene en cuenta hasta que haya que enviar la versión final.

Y no te puedes hacer una idea de lo que ocupará (en el formato final) hasta que esté terminado.

Pero haz lo que veas.

De: Paloma de las Cuevas Delgado [mailto:notifications@github.com] 
Enviado el: miércoles, 15 de abril de 2015 12:02
Para: geneura-papers/2014-2015-COMCOM-MUSES_vs_SotA_BYOD_Systems
CC: Antonio Mora
Asunto: Re: [2014-2015-COMCOM-MUSES_vs_SotA_BYOD_Systems] Enganchar bien las secciones (#5)

Uhm, no lo veo bien, porque normalmente trabajamos directamente con el formato que se envía, o ¿es que para esta revista no es así? Además, si nos ajustamos al lo que piden, ya lo hemos hecho bien y no hay que re-revisar-re-escribir-re-resumir... vaya, el doble de trabajo.

—
Reply to this email directly or view it on GitHub https://github.com/geneura-papers/2014-2015-COMCOM-MUSES_vs_SotA_BYOD_Systems/issues/5#issuecomment-93299440 .  https://github.com/notifications/beacon/AC6-WsmIs_V6yYnjDqYjzduJlByD19VKks5n_i6bgaJpZM4DzSzT.gif 

No se encontraron virus en este mensaje.
Comprobado por AVG - www.avg.com
Versión: 2015.0.5863 / Base de datos de virus: 4331/9542 - Fecha de publicación: 04/15/15

---

No se encontraron virus en este mensaje.
Comprobado por AVG - www.avg.com
Versión: 2015.0.5863 / Base de datos de virus: 4331/9534 - Fecha de publicación: 04/14/15

**Comment by JJ** [comment]
Estoy de acuerdo con Antonio. Es difícil predecir en cuantas páginas a
doble columna se va a quedar y es mejor no recortar hasta que no sea
estrictamente necesario.

**Comment by unintendedbear** [comment]
Ya, por eso preguntaba al principio que si es que en las revistas es así, jeje. Pues nada, así se queda.
