### ISSUE TITLE
Considerar claramente los objetivos del trabajo

### ISSUE THREAD

**Issue by JJ** [geneura-papers/2014-2015-COMCOM-MUSES_vs_SotA_BYOD_Systems#6]
Ahora mismo parecen ser
1. Contar lo importante que es una IPS.
2. Contar qué herramientas BYOD hay en el mercado
3. Contar qué es Muses.

¿Cuáles son los objetivos? ¿Cuál es el selling point? ¿Vamos a aumentarlo con resultados ya obtenidos o lo vamos a dejar en exposición de intenciones?
Esto para los dos @amorag @unintendedbear (y quien quiera apuntarse)

**Comment by unintendedbear** [comment]
Estoy de acuerdo en aumentarlo con los resultados ya obtenidos. La idea al principio era contar un poco el estado del arte en BYOD y luego incluir MUSES y el cómo MUSES era mejor que las otras.

**Comment by JJ** [comment]
En ese caso, ¿cuál es el objetivos?

¿Qué mejora Muses? ¿La seguridad? ¿Cómo se mide eso?

**Comment by JJ** [comment]
EStos issues habría que irlos cerrando...

**Comment by JJ** [comment]
Lo cierro y ya.
