### ISSUE TITLE
Revisar el inglés

### ISSUE THREAD

**Issue by JJ** [geneura-papers/2014-2015-COMCOM-MUSES_vs_SotA_BYOD_Systems#7]
Revisar la gramática y por supuesto el spelling. Primera candidata a revisar: @aesparcia o @fergunet

**Comment by fergunet** [comment]
Agh, no había puesto enlace al issue en este commit b216d703e72bb2b554268c2aed1867bbb6068c35

**Comment by JJ** [comment]
No estaría mal revisarlo de nuevo de cabo a rabo.

**Comment by JJ** [comment]
Pues eso...

**Comment by unintendedbear** [comment]
Yo lo estoy revisando/corrigiendo conforme voy cerrando mis issues. Cuando acabe con ellos iré revisando el resto. Pedro también va revisando el inglés cuando se hace un cambio.
